name: Deploy Production 🚀

on:
  release:
    types:
      - published
      - edited

jobs:
  deploy-production:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Execute Deployment Command
        uses: appleboy/ssh-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          APP_PROD_PATH: ${{ vars.APP_PROD_PATH }}
          APP_PROD_PORT: ${{ secrets.APP_PROD_PORT }}
          APP_TAG: ${{ github.event.release.tag_name }}
          GIT_URL: ${{ secrets.GIT_URL }}
          MINIO_PROD_ENDPOINT: ${{ secrets.MINIO_PROD_ENDPOINT }}
          MINIO_PROD_ACCESS_KEY: ${{ secrets.MINIO_PROD_ACCESS_KEY }}
          MINIO_PROD_SECRET_KEY: ${{ secrets.MINIO_PROD_SECRET_KEY }}

        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN,APP_PROD_PATH,APP_PROD_PORT,APP_TAG,GIT_URL,MINIO_PROD_ENDPOINT,MINIO_PROD_ACCESS_KEY,MINIO_PROD_SECRET_KEY
          script: |

            if [[ -d "/home/ubuntu/${APP_PROD_PATH}" ]]; then
              cd $APP_PROD_PATH
              sudo docker compose down pacmusic-prod
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL $APP_PROD_PATH
              cd $APP_PROD_PATH
            fi 

            # Create or update the .env file
            echo "APP_IMAGE=$DOCKERHUB_USERNAME/pacmusic" > .env
            echo "APP_TAG=$APP_TAG" >> .env
            echo "APP_PROD_PORT=$APP_PROD_PORT" >> .env
            echo "MINIO_PROD_ENDPOINT=$MINIO_PROD_ENDPOINT" >> .env
            echo "MINIO_PROD_ACCESS_KEY=$MINIO_PROD_ACCESS_KEY" >> .env
            echo "MINIO_PROD_SECRET_KEY=$MINIO_PROD_SECRET_KEY" >> .env

            # Run app
            sudo docker compose up --build --detach pacmusic-prod

      - name: Hit Endpoint
        run: |
          sleep 20
          curl ${{ secrets.PROD_URL }}
